"""Regression tests for metadata generated by the upstream PR workflow."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

REPO = Path(__file__).resolve().parent.parent


def _render_workflow_script() -> str:
    registry = yaml.safe_load((REPO / "providers.yml").read_text(encoding="utf-8"))
    providers = [
        provider
        for provider in registry["providers"]
        if provider.get("provider_type") != "server_fork"
    ]
    base = providers[0]
    env = Environment(
        loader=FileSystemLoader(str(REPO / "wrappers")),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    rendered = env.get_template("upstream-pr.yml.j2").render(
        domain=base["domain"],
        display_name=base["display_name"],
        manifest_path=base["manifest_path"],
        provider_path=base["provider_path"],
        provider_type=base["provider_type"],
        locale=base.get("locale", "en"),
        repo=base["repo"],
        default_branch=base["default_branch"],
        service_url=base.get("service_url", ""),
        auth_method=base.get("auth_method", ""),
        max_quality=base.get("max_quality", ""),
        features=base.get("features", []),
        codespell_ignore_words=base.get("codespell_ignore_words", ""),
        github_description=base.get("github_description", ""),
        github_topics=base.get("github_topics", []),
        github_homepage=base.get("github_homepage", ""),
        related_providers=base.get("related_providers", []),
        all_providers=providers,
    )
    workflow = yaml.safe_load(rendered)
    return workflow["jobs"]["create-upstream-pr"]["steps"][2]["run"]


def _fragment(script: str, start: str, end: str) -> str:
    return script.split(start, 1)[1].split(end, 1)[0]


def _run_shell(fragment: str, **environment: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "-euo", "pipefail", "-c", fragment],
        env={**os.environ, **environment},
        capture_output=True,
        text=True,
        check=False,
    )


def test_release_title_is_user_facing() -> None:
    """A conventional-commit prefix must not break upstream PR metadata checks."""
    script = _render_workflow_script()
    fragment = _fragment(script, "# Generate PR title", "# Get changelog data")
    fragment = fragment.replace("${{ inputs.pr_summary }}", "$PR_SUMMARY_INPUT")
    result = _run_shell(
        fragment + '\nprintf "%s" "$PR_TITLE"',
        DOMAIN="yandex_music",
        DISPLAY_NAME="Yandex Music",
        VERSION="v3.8.8",
        PREV_TAG="v3.8.7",
        PR_SUMMARY_INPUT="shared playlist requests",
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout == (
        "Update Yandex Music provider to v3.8.8: shared playlist requests"
    )


def test_body_selects_one_type_and_confirms_completed_checks() -> None:
    """Generated metadata must satisfy upstream's label and checklist contracts."""
    script = _render_workflow_script()
    fragment = _fragment(
        script,
        '# Determine which "Types of changes" box gets ticked. Upstream accepts exactly',
        "# Defense-in-depth",
    )
    fragment = fragment.replace("${{ inputs.change_type }}", "$CHANGE_TYPES_INPUT")
    result = _run_shell(
        fragment + '\nprintf "%s" "$PR_BODY"',
        CHANGE_TYPES_INPUT="bugfix,maintenance,dependencies",
        PREV_TAG="v3.8.7",
        DISPLAY_NAME="Yandex Music",
        VERSION="v3.8.8",
        PROVIDER_REPO="trudenboy/ma-provider-yandex-music",
        COMPARE_LABEL="vs v3.8.7",
        WHAT_NEW="- Fix playlist request sharing",
        FILES_SECTION="_No files changed_",
        HUMAN_COAUTHORS="",
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout.count("- [x]") == 5
    assert "- [x] Bugfix" in result.stdout
    assert "- [ ] Maintenance / chore" in result.stdout
    assert "- [ ] Dependencies bump" in result.stdout
    assert "- [x] The code change is tested and works locally." in result.stdout
    assert "- [x] `pre-commit run --all-files` passes." in result.stdout
    assert "- [x] `pytest` passes" in result.stdout
    assert "- [x] I have read and complied with the project's [AI Policy]" in result.stdout
